export const ADD_CONTACTUS_DATA='ADD_CONTACTUS_DATA';
export const DELETE_CONTACTUS_DATA='DELETE_CONTACTUS_DATA';
export const EDIT_CONTACTUS_DATA='EDIT_CONTACTUS_DATA';
export const EMPTY_CONTACTUS_DATA='EMPTY_CONTACTUS_DATA'




