export const ADD_TIMELINE_DATA='ADD_TIMELINE_DATA';
export const DELETE_TIMELINE_DATA='DELETE_TIMELINE_DATA';
export const EDIT_TIMELINE_DATA='EDIT_TIMELINE_DATA';
export const EMPTY_TIMELINE_DATA='EMPTY_TIMELINE_DATA';
export const SET_BOOKED_SLOTS = "SET_BOOKED_SLOTS";




